baseURL = "/"
languageCode = "en-us"
title = "Random Bluesky Fact"

disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT"]

[params]
  description = "A random interesting fact from Bluesky."

